plane_img = pygame.image.load('Assets/plane.png')
logo_img = pygame.image.load('Assets/logo.png')
fighter_img = pygame.image.load('Assets/fighter.png')
clouds_img = pygame.image.load('Assets/clouds.png')
clouds_img = pygame.transform.scale(clouds_img, (WIDTH, 350))

home_img=pygame.image.load("Assets/Buttons/homeBtn.png")
replay_img=pygame.image.load("Assets/Buttons/Reply.png")
sound_off_img=pygame.image.load("Assets/Buttons/soundOffBtn.png")
sound_on_img=pygame.image.load("Assets/Buttons/soundOnBtn.png")
